#!/bin/sh
PHP_INI_SCAN_DIR='/var/www/u3380804/data/php-bin-regru-php83/sabirov.tech:'
PHPRC='/var/www/u3380804/data/php-bin-regru-php83'
export PHP_INI_SCAN_DIR
export PHPRC
exec /opt/php/8.3/bin/php-cgi
